version: '3.9'

services:

  hyperf-crud:
    container_name: hyperf-crud
    image: hyperf/hyperf:8.2-alpine-v3.18-swoole
    working_dir: /data/project
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    volumes:
      - ./webserver:/data/project
    ports:
      - 9501:9501
    depends_on:
      - hyperf-crud-mariadb
      - hyperf-crud-redis

  hyperf-crud-mariadb:
    container_name: hyperf-crud-mariadb
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "hyperf-crud"

  hyperf-crud-redis:
    container_name: hyperf-crud-redis
    image: redis:latest
    ports:
      - 6379:6379